# This composition including its keys are used for development purposes only.
# See the README.md for installation notes.
version: "3.1"

services:

  postgres_products_service:
    container_name: postgres_products_service
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:10.4-alpine
    environment:
      POSTGRES_DB: products_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data/
    restart: always

  products_service:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint-dev.sh
    container_name: productsservice
    image: products_service
    volumes:
      - .:/code
    ports:
      - "8003:8080"
    depends_on:
      - postgres_products_service
    environment:
      ALLOWED_HOSTS: localhost,127.0.0.1,productsservice
      CORS_ORIGIN_WHITELIST: localhost,127.0.0.1,localhost:4200
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "products_service"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres_products_service"
      DATABASE_PORT: "5432"
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: "products_service.settings.base"
      JWT_PUBLIC_KEY_RSA_BUILDLY: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB
        qhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==
        -----END PUBLIC KEY-----
      SECRET_KEY: "oxcdb=mtcc7q1cym@oox(lyrz1ncz-(w+(#&u7l-&)7a8wvxyz"
      AWS_ACCESS_KEY_ID: example
      AWS_SECRET_ACCESS_KEY: example
      AWS_STORAGE_BUCKET_NAME : example
